# Generated by Django 3.2.8 on 2022-10-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(max_length=255),
        ),
    ]
